### ISSUE TITLE
activating "mike-lischke.vscode-antlr4” failed

### ISSUE THREAD

**Issue by aruanruan** [mike-lischke/antlr4-graps#4]
activating extension “mike-lischke.vscode-antlr4” failed: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\xxxx\.vscode\extensions\mike-lischke.vscode-antlr4-0.4.2\node_modules\antlr4-graps\bin\windows\antlr4_graps.node。

**Comment by mike-lischke** [comment]
Can you be a bit more specific what you did when you got this error? It doesn't tell me much and there is no bin/ folder in the antlr4-graps node module.

**Comment by aruanruan** [comment]
all node module exists, but my os is windows 10 / 64bit,  some other bug reports of other node modules on  internet say this is 32bts dll target, can not run on 64 bits os.

**Comment by aruanruan** [comment]
sorry, it is too old for my vscode
