### ISSUE TITLE
Unpublished?

### ISSUE THREAD

**Issue by gcampbell-epiq** [mike-lischke/antlr4-graps#5]
I used this for an electron-based antlr editor i threw together. This library is very helpful, but it looks like its been unpublished from npm. Any chance of getting it back up? Thanks! And nice work!

**Comment by mike-lischke** [comment]
I haven't got any feedback when I announced that this library will be merged with the the vscode-antlr4 extension. It produces quite some extra work to maintain antlr4-graps separately, so I decided to give up on the separate lib and integrate it instead into the extension. I have no plan to reopen work on this module and will remove the repo sooner or later.

What you can do is to use the vscode extension and extract the relevant code into an own module if you want that separately (see the [backend](https://github.com/mike-lischke/vscode-antlr4/tree/master/src/backend) folder).
